version: '3.4'

services:
  dvdstore.api:
    image: ${DOCKER_REGISTRY-}dvdstoreapi
    build:
      context: .
      dockerfile: DVDStore.Api/Dockerfile
    environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_URLS: http://*:4900
    ports:
       - 4900:4900
    depends_on:
       - dvdstore.db
  dvdstore.db:
    image: postgres:latest
    restart: always
    ports:
        - 5432:5432
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: MyStrongPassword!
       POSTGRES_DB: DVD_DOCKER
volumes:
  pgdata: