version: '3.4'

services:
  dvdstore.api:
    image: ${DOCKER_REGISTRY-}dvdstoreapi
    build:
      context: .
      dockerfile: DVDStore.Api/Dockerfile
    environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_URLS: http://*:4900
    ports:
       - 4900:4900
    depends_on:
       - dvdstore.db
  dvdstore.db:
    image: postgres:latest
    restart: always
    ports:
        - 4901:5432
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./dbscripts/dvdstore-init.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
       POSTGRES_HOST_AUTH_METHOD: scram-sha-256
       POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: MyStrongPassword!
       POSTGRES_DB: dvdrental
volumes:
  pgdata: